package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/cyucelen/isola/internal/cert"
	"github.com/cyucelen/isola/internal/registry"
	"github.com/cyucelen/isola/internal/trust"
	"github.com/spf13/cobra"
)

var trustCmd = &cobra.Command{
	Use:   "trust",
	Short: "Install the isola CA certificate into the system trust store",
	Long: `Install the isola development CA certificate into the system trust store
so that browsers and other tools trust HTTPS certificates generated by isola.

On macOS, this adds the certificate to the System keychain; on Linux, it copies
the certificate into /usr/local/share/ca-certificates and runs
update-ca-certificates. Both require sudo, so you may be prompted for your
password.

isola normally does this for you on the first HTTPS 'isola up' in a terminal;
run this command to (re)install trust manually. Run 'isola up' (with HTTPS) or
'isola proxy start --https' first to generate the CA certificate.`,
	Annotations: map[string]string{"skipRepoDetection": "true"},
	RunE: func(cmd *cobra.Command, args []string) error {
		gdir, err := registry.GlobalDir()
		if err != nil {
			return err
		}
		caPath := cert.CAPath(filepath.Join(gdir, "certs"))
		if _, err := os.Stat(caPath); os.IsNotExist(err) {
			return fmt.Errorf("CA certificate not found at %s\nRun 'isola up' (with HTTPS) or 'isola proxy start --https' first to generate certificates", caPath)
		}
		if !trust.Supported() {
			fmt.Printf("Automatic trust store installation is not supported on this OS.\nPlease manually install the CA certificate:\n  %s\n", caPath)
			return nil
		}
		fmt.Println("Installing the isola CA into the system trust store; you may be prompted for your password.")
		if err := trust.Install(caPath); err != nil {
			return fmt.Errorf("installing CA certificate: %w", err)
		}
		fmt.Println("✓ CA certificate installed.")
		return nil
	},
}

func init() {
	rootCmd.AddCommand(trustCmd)
}
